spring:
  application:
    name: cloud-producer
  profiles:
    active: dev
  cloud:
    nacos:
      discovery: #注册中心
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PWD:nacos}
        namespace: 74193cd9-fac4-4f2a-addc-47c60508b15c
        cluster-name: DEFAULT  # 集群名称，保持一致
      config: #配置中心
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PWD:nacos}
        file-extension: yaml
        namespace: 74193cd9-fac4-4f2a-addc-47c60508b15c
  config:
    import: #指定加载配置的方式以及文件
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:seata-common.yaml
      - nacos:rocketmq-common.yaml